### ISSUE TITLE
Can't build zbus

### ISSUE THREAD

**Issue by 0323pin** [grtcdr/citron#1]
Hi,

So, I've tried to build `citron` but, I can't build `zbus` :(
Not your fault, though.

```
   Compiling zbus v1.9.1
error[E0432]: unresolved import `nix::sys::socket::sockopt::PeerCredentials`
   --> /usr/pkgsrc/wip/citron/work/vendor/zbus-1.9.1/src/connection.rs:163:44
    |
163 |         use nix::sys::socket::{getsockopt, sockopt::PeerCredentials};
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ no `PeerCredentials` in `sys::socket::sockopt`

error[E0432]: unresolved import `nix::sys::socket::sockopt::PeerCredentials`
   --> /usr/pkgsrc/wip/citron/work/vendor/zbus-1.9.1/src/azync/connection.rs:180:44
    |
180 |         use nix::sys::socket::{getsockopt, sockopt::PeerCredentials};
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ no `PeerCredentials` in `sys::socket::sockopt`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `zbus` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

Should look into `connection.rs` but, don't have the time right now.

**Comment by grtcdr** [comment]
I'll look into this, thanks for reporting!

**Comment by 0323pin** [comment]
If it helps here's the Makefile I've created,

```
# $NetBSD$

DISTNAME=	citron-0.1.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_GITHUB:=grtcdr/}
GITHUB_PROJECT=	citron
GITHUB_TAG=	18af985db562bec6318636e3672b7171b090e1a7

MAINTAINER=	pin@NetBSD.org
HOMEPAGE=	https://github.com/grtcdr/citron/
COMMENT=	Ditch your panel for some snazzy desktop notifications
LICENSE=	mit

.include "cargo-depends.mk"

INSTALLATION_DIRS=	bin

RUSTFLAGS+=	-C link-arg=${COMPILER_RPATH_FLAG}${BUILDLINK_PREFIX.dbus}/lib

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/target/release/citron ${DESTDIR}${PREFIX}/bin

.include "../../lang/rust/cargo.mk"
.include "../../sysutils/dbus/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
```

**Comment by grtcdr** [comment]
I'll try and make it so it defaults to dbus (for NetBSD) [with the `d` feature](https://github.com/hoodie/notify-rust#d).

**Comment by grtcdr** [comment]
DBUS is now the default (for everyone), it drops the dependencies by A LOT and we shouldn't miss out on anything according to the link I previously sent.

You should be able to build now :)

**Comment by 0323pin** [comment]
Awesome, I'll give it a go tomorrow morning.

**Comment by grtcdr** [comment]
I've created a tag for v0.2.0 in case you want to use that ;)

**Comment by 0323pin** [comment]
@grtcdr Ok, it builds and installs. What do I need to do for it to work? Do I need to install a notification service? Right now I can see anything being printed out. I'm sure this should work, it's most probably because I have no notification daemon running.

One more question, did you understood what was the issue with `zbus`? I saw `leftwm` is planning on adding `zbus` and that will break the NetBSD build as is right now.

Thanks!

**Comment by grtcdr** [comment]
The zbus crate is [Linux specific](https://docs.rs/zbus/latest/zbus/) while the dbus one is not.

As far as notifications go, did you try running one of the commands listed in the usage example?

**Comment by grtcdr** [comment]
> Yes, there's no terminal output. Hence my question. 

citron doesn't have any terminal output (if a readout fails, it'll say so in the notification itself), but I'll try and work on a debug feature in case notifications are unable to show for whatever or the daemon's capabilities are lacking.

> Is it working for you with 0.2.0?

Yes, it's working as intended.

**Comment by 0323pin** [comment]
@grtcdr what I suspected, it's just me knowing nothing about notifications. I can set-up the whole lxqt desktop and see if they show-up.

**Comment by grtcdr** [comment]
I'll add the prerequisites to the README to avoid any future confusion.

**Comment by grtcdr** [comment]
Hey, quick question, what's the most *nix agnostic place to search for installed libraries?

**Comment by 0323pin** [comment]
NetBSD har `/usr/lib` for base and `/usr/pkg/lib` for user installed packages. FreeBSD, OpenBSD and DragonFly will have them in `/usr/local`.

Now, on NetBSD if they belong to xorg, they could be in `/usr/X11R7/lib`. Any particular library you are looking for?

Yes, I've installed `lxqt-notificationd` but, without the desktop it didn't work but, ... it could be because I didn't start the daemon 😮‍💨 
Also tried installing `tiramisu` but, I have no clue how to use it.

Need to check it out with the lxqt daemon again. I'm really sorry for the noise.

If I get it to work, do you have anything against merging the package?

**Comment by grtcdr** [comment]
I'm trying to build a function that searches for a library (libdbus in this case) without resorting to `ldconfig -p`. Thanks for all the information!

> If I get it to work, do you have anything against merging the package?

In pkgsrc? Of course not, I'd be honored :heart:

Before that happens though, I have to hack together this debug logic.

**Comment by 0323pin** [comment]
No rush man, I can wait for the _green light_

> I'm trying to build a function that searches for a library (libdbus in this case)

I've already told the compiler where to find it, so the binary will know, this Line in the above Makefile, `RUSTFLAGS+=	-C link-arg=${COMPILER_RPATH_FLAG}${BUILDLINK_PREFIX.dbus}/lib`

The beauty of pkgsrc :smile
It will work on all supported platforms.

**Comment by 0323pin** [comment]
@grtcdr ok,
NetBSD, `/usr/pkg/lib/libdbus`
FreeBSD, DragonFly and OpenBSD `/usr/local/lib/libdbus`

**Comment by grtcdr** [comment]
`--debug` is in with the latest https://github.com/grtcdr/citron/commit/6a89aca46b9e0a160207a6735f84e7b83659c49f

I still need to add a bunch of daemons to the list, time to hit up the Arch wiki.

**Comment by 0323pin** [comment]
> `--debug` is in with the latest [6a89aca](https://github.com/grtcdr/citron/commit/6a89aca46b9e0a160207a6735f84e7b83659c49f)
> 
> I still need to add a bunch of daemons to the list, time to hit up the Arch wiki.

Or just say any notification daemon.

**Comment by grtcdr** [comment]
I ditched `find_daemons()` in https://github.com/grtcdr/citron/commit/90fc4e5e257fd5f011e341503673e7e78b29ec58, notify-rust's `get_capabilities()` is enough to determine whether a notification daemon is running/installed.

**Comment by grtcdr** [comment]
All done! `--version` and `--debug` are both in, I've published a tag as well to go along with the cargo release.

**Comment by 0323pin** [comment]
@grtcdr 😆 

https://i.postimg.cc/cHQw0ykN/2021-12-06-213441-1366x768-scrot.png

**Comment by grtcdr** [comment]
Beautiful :heart:

What typeface is that in the notification?

**Comment by 0323pin** [comment]
Montserrat, https://github.com/JulietaUla/Montserrat

Packaged by ... guess who 🤣 ?
The deamon is `lxqt-notificationd` and the Qt5-theme by myself, https://codeberg.org/pin/leftwm-netbsd/src/branch/main/home/.config/qt5ct/colors/oxide.conf

**Comment by 0323pin** [comment]
Are you ok if I merge the package now?

**Comment by grtcdr** [comment]
> Montserrat, https://github.com/JulietaUla/Montserrat
> 
> Packaged by ... guess who :rofl: ?

I'm gonna make a wild guess... _you_ :D

 The deamon is `lxqt-notificationd` and the Qt5-theme by myself, https://codeberg.org/pin/leftwm-netbsd/src/branch/main/home/.config/qt5ct/colors/oxide.conf

It's a pleasant colorscheme, I like the shadows... dang I haven't seen shadows in a long time.

> Are you ok if I merge the package now?

Yep!

**Comment by 0323pin** [comment]
@grtcdr Thank you! Package merged now.

**Comment by 0323pin** [comment]
Evidence, https://mail-index.netbsd.org/pkgsrc-changes/2021/12/06/msg244589.html

**Comment by grtcdr** [comment]
> Evidence

I don't know why, maybe it's the choice of words, but this made me laugh at loud :laughing:

**Comment by grtcdr** [comment]
Thanks by the way :heart:

**Comment by 0323pin** [comment]
> > Evidence
> 
> I don't know why, maybe it's the choice of words, but this made me laugh out loud 😆

Hmm... 👍

**Comment by grtcdr** [comment]
Don't take it the wrong way, it's probably because of the enormous amounts of memes I used to consume.

**Comment by 0323pin** [comment]
Don't worry, I didn't.
